### ISSUE TITLE
Access to the path ...\Luke\AppData\... is denied. 

### ISSUE THREAD

**Issue by clemmyn23** [Luciusp/ffxiv-act-installer#1]
https://github.com/Luciusp/ffxiv-act-installer/blob/32424b147f2296e0215c2238008fb9e275c64e46/ffxiv-act-installer/act-config/Advanced%20Combat%20Tracker.config.xml#L424-L430

![image](https://user-images.githubusercontent.com/6946253/51788235-b5968c00-21cf-11e9-9ec7-90f7d358c472.png)

**Comment by Luciusp** [comment]
Working on a fix.

**Comment by Luciusp** [comment]
Fixed in latest version.
